import { currentAdminRequest } from "./auth.js";
import { escapeHtml as e } from "./utils.js";

export function renderLogin(message = "") {
  return `<main id="main" tabindex="-1"><section class="auth-page"><div class="auth-art"><img src="assets/likha-logo.png" alt="LIKHA Arts Club logo"><p class="eyebrow">Arts club · NU Cebu</p><h1>Welcome back<br>to the studio.</h1></div><div class="auth-content"><p class="eyebrow">Member and administrator sign in</p><h2>Sign in to LIKHA</h2><p>Your role is assigned by the club. There is no public admin registration.</p><form data-form="login" novalidate><label>School email<input name="email" type="email" autocomplete="username" required maxlength="254"></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><p class="form-error" data-form-error role="alert">${e(message)}</p><button class="button button-primary" type="submit">Sign in</button></form><button type="button" class="text-link auth-reset" data-action="forgot-password">Forgot password?</button><div class="auth-divider"><span>New to LIKHA?</span></div><a class="button button-outline-dark" href="#/join">Register as a member</a><p class="auth-admin-note">Administrator access is granted only after Main Admin approval. <a href="#/access">Request access</a></p><a class="back-link" href="#/">← Back to website</a></div></section></main>`;
}

export async function renderAccessRequest(profile) {
  if (!profile) return `<main id="main" tabindex="-1"><section class="section wrap">${notice("Sign in first", "Admin access requests are tied to a verified LIKHA member account.", '<a class="button button-primary" href="#/login">Sign in</a>')}</section></main>`;
  if (profile.role === "main_admin" || profile.role === "sub_admin") return `<main id="main" tabindex="-1"><section class="section wrap">${notice("Administrator access is active", `Your current role is ${profile.role === "main_admin" ? "Main Admin" : "Sub-Admin"}.`, '<a class="button button-primary" href="#/admin">Open dashboard</a>')}</section></main>`;
  const request = await currentAdminRequest(profile.id);
  if (request?.status === "pending") return `<main id="main" tabindex="-1"><section class="section wrap">${notice("Request pending", "A Main Admin will review your request. Your member account remains available while you wait.", '<a class="text-link" href="#/account">Account settings</a>')}</section></main>`;
  if (request?.status === "rejected") return `<main id="main" tabindex="-1"><section class="section wrap">${notice("Request not approved", "You can contact LIKHA through the club's community channels if you have questions.", '<a class="text-link" href="#/community">Community links</a>')}</section></main>`;
  return `<main id="main" tabindex="-1"><section class="section wrap access-layout"><div><p class="eyebrow">Administrator access</p><h1>Request Sub-Admin access</h1><p class="section-lede">Requests are reviewed by the Main Admin. Approval grants only the permissions assigned to your account.</p><div class="permission-list"><h2>Possible Sub-Admin permissions</h2><ul><li>Manage artworks and artist profiles</li><li>Update Atelier content</li><li>Moderate open chat</li><li>Restrict members when authorized</li></ul><p>Main Admin settings and user management stay restricted.</p></div></div><form class="form-panel" data-form="admin-request"><p class="eyebrow">Signed in as</p><h2>${e(profile.full_name)}</h2><p>${e(profile.email)}</p><label>Why would you like to help moderate LIKHA?<textarea name="reason" required minlength="20" maxlength="1200" rows="5"></textarea></label><p class="form-error" data-form-error role="alert"></p><button class="button button-primary" type="submit">Send request</button></form></section></main>`;
}

export function renderAccount(profile) {
  if (!profile) return renderLogin();
  return `<main id="main" tabindex="-1"><section class="page-heading"><div class="wrap"><p class="eyebrow">Your membership</p><h1>Account</h1><p>Manage the profile details shown to LIKHA administrators and choose your name for chat.</p></div></section><section class="section wrap account-layout"><form class="form-panel" data-form="account"><div class="account-role"><span class="eyebrow">Account role</span><strong>${e(profile.role === "main_admin" ? "Main Admin" : profile.role === "sub_admin" ? "Sub-Admin" : "LIKHA Member")}</strong><span>${e(profile.membership_status || "active")}</span></div><label>Full name<input name="full_name" value="${e(profile.full_name)}" required maxlength="100"></label><label>Chat display name<input name="display_name" value="${e(profile.display_name || "")}" required maxlength="40"></label><label>Community role<select name="community_type"><option value="student"${profile.community_type === "student" ? " selected" : ""}>Student</option><option value="faculty"${profile.community_type === "faculty" ? " selected" : ""}>Faculty</option><option value="staff"${profile.community_type === "staff" ? " selected" : ""}>Staff</option></select></label><label>Course or department<input name="course" value="${e(profile.course || "")}" maxlength="100"></label><label>Year level<select name="year_level"><option value="">Not applicable</option>${["1st year", "2nd year", "3rd year", "4th year", "5th year", "Graduate"].map(item => `<option${profile.year_level === item ? " selected" : ""}>${item}</option>`).join("")}</select></label><label>Contact detail<input name="contact_info" value="${e(profile.contact_info || "")}" maxlength="60"></label><label>Artistic interests<input name="interests" value="${e(profile.interests?.join(", ") || "")}" maxlength="250"></label><p class="form-error" data-form-error role="alert"></p><div class="account-actions"><button class="button button-primary" type="submit">Save profile</button><button class="button button-quiet" type="button" data-action="logout">Sign out</button></div></form><aside class="account-side"><p class="eyebrow">School email</p><p>${e(profile.email)}</p><p class="account-status">Account status: ${e(profile.account_status || "active")}</p>${profile.role === "member" ? `<a class="text-link" href="#/access">Request Sub-Admin access <span aria-hidden="true">↗</span></a>` : ""}</aside></section></main>`;
}

export function renderPasswordReset() {
  return `<main id="main" tabindex="-1"><section class="auth-page auth-reset-page"><div class="auth-content"><p class="eyebrow">Account security</p><h1>Set a new password</h1><form data-form="reset-password"><label>New password<input name="password" type="password" autocomplete="new-password" minlength="10" required></label><label>Confirm password<input name="confirm_password" type="password" autocomplete="new-password" minlength="10" required></label><p class="form-error" data-form-error role="alert"></p><button class="button button-primary" type="submit">Update password</button></form></div></section></main>`;
}

function notice(title, body, action) {
  return `<div class="empty-state"><span class="empty-mark" aria-hidden="true">L</span><h1>${e(title)}</h1><p>${e(body)}</p>${action}</div>`;
}
